import { test, expect } from '@playwright/test';

// Codegen baseline captured for HU-02 seller management flow.
// It is skipped because this raw recording contains exploratory clicks and must be refactored into POM before running in the suite.
test.skip('HU-02 codegen base: gestion de productos como vendedor', async ({ page }) => {
  await page.goto('https://qaxpert.com/lab/sites/stage-4/marketplace/index.html');
  await expect(page.getByRole('heading', { name: 'Bienvenido a QAXmarket' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Soy Vendedor' })).toBeVisible();
  await page.getByRole('heading', { name: 'Soy Vendedor' }).click();
  await expect(page.getByRole('heading', { name: 'Mis Productos' })).toBeVisible();
  await expect(page.getByText('Vendedor')).toBeVisible();
  await expect(page.getByRole('link', { name: 'Cambiar a Comprador' })).toBeVisible();
  await expect(page.getByRole('link', { name: '+ Publicar Nuevo Producto' })).toBeVisible();
  await expect(page.getByRole('link', { name: '+ Publicar Nuevo Producto' })).toBeVisible();
  await page.getByRole('link', { name: '+ Publicar Nuevo Producto' }).click();
  await page.getByRole('textbox', { name: 'Nombre del Producto' }).click();
  await page.getByRole('textbox', { name: 'Nombre del Producto' }).fill('Nintendo Switch OLED');
  await page.getByRole('textbox', { name: 'Nombre del Producto' }).press('Tab');
  await page.getByRole('textbox', { name: 'DescripciÃ³n' }).fill('Nintendo Switch OLED con motivo de Tears of the Kingdom');
  await page.getByLabel('CategorÃ­a').selectOption('Juguetes y Juegos');
  await page.getByRole('spinbutton', { name: 'Precio (COP)' }).click();
  await page.getByRole('spinbutton', { name: 'Precio (COP)' }).fill('1800000');
  await page.getByRole('spinbutton', { name: 'Stock Disponible' }).click();
  await page.getByRole('spinbutton', { name: 'Stock Disponible' }).fill('5');
  await page.getByText('ðŸ“· Arrastra una imagen aquÃ­ o').click();
  await page.getByText('(Simulado â€” se usarÃ¡').click();
  await page.locator('#prodImage').setInputFiles('msedge_jM7G66ocJo.png');
  await expect(page.getByRole('heading', { name: 'Publicar Nuevo Producto' })).toBeVisible();
  await expect(page.getByText('Nombre del Producto')).toBeVisible();
  await expect(page.getByText('DescripciÃ³n')).toBeVisible();
  await expect(page.getByText('CategorÃ­a', { exact: true })).toBeVisible();
  await expect(page.getByText('Precio (COP)')).toBeVisible();
  await expect(page.getByText('Stock Disponible')).toBeVisible();
  await expect(page.getByRole('textbox', { name: 'Nombre del Producto' })).toBeVisible();
  await expect(page.getByRole('textbox', { name: 'DescripciÃ³n' })).toBeVisible();
  await expect(page.getByLabel('CategorÃ­a')).toBeVisible();
  await expect(page.getByRole('spinbutton', { name: 'Precio (COP)' })).toBeVisible();
  await expect(page.getByRole('spinbutton', { name: 'Stock Disponible' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Publicar Producto' })).toBeVisible();
  await page.getByRole('button', { name: 'Publicar Producto' }).click();
  await expect(page.getByRole('heading', { name: 'Mis Productos' })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'Nintendo Switch OLED' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Ã“rdenes Recibidas' })).toBeVisible();
  await page.getByRole('link', { name: 'Ã“rdenes Recibidas' }).click();
  await expect(page.getByRole('heading', { name: 'Ã“rdenes Recibidas' })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'ID' })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Comprador' })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Producto(s)' })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Total' })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Estado' })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Fecha' })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'AcciÃ³n' })).toBeVisible();
  await page.getByRole('cell', { name: 'Laura Torres' }).click();
  await page.getByRole('cell', { name: 'Laura Torres' }).click();
  await page.getByRole('cell', { name: 'Laura Torres' }).click();
  await page.getByRole('link', { name: 'â† Mis Productos' }).click();
  await page.getByRole('button', { name: 'Editar' }).nth(5).click();
  await page.getByRole('link', { name: 'â† Mis Productos' }).click();
  await page.getByRole('cell', { name: 'Nintendo Switch OLED' }).click();
  await expect(page.getByRole('button', { name: 'Eliminar' }).nth(1)).toBeVisible();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Eliminar' }).nth(1).click();
  await page.getByRole('link', { name: 'Ã“rdenes Recibidas' }).click();
  await page.getByRole('link', { name: 'â† Mis Productos' }).click();
  await page.getByRole('link', { name: 'Cambiar a Comprador' }).click();
  await page.getByText('ðŸ›’ Soy Comprador Explora').click();
  await page.locator('div:nth-child(15) > .img-placeholder').click();
  await page.getByRole('button', { name: 'Agregar al Carrito' }).click();
  await page.getByRole('link', { name: 'ðŸ›’ Carrito (1)' }).click();
  await expect(page.getByRole('heading', { name: 'Carrito de Compras' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Ir a Pagar' })).toBeVisible();
  await page.getByRole('link', { name: 'Ir a Pagar' }).click();
  await page.getByRole('textbox', { name: 'Nombre Completo' }).click();
  await page.getByRole('textbox', { name: 'Nombre Completo' }).fill('Luis QA');
  await page.getByRole('textbox', { name: 'Nombre Completo' }).press('Tab');
  await page.getByRole('textbox', { name: 'DirecciÃ³n' }).fill('Calle Falsa 123');
  await page.getByRole('textbox', { name: 'DirecciÃ³n' }).press('Tab');
  await page.getByRole('textbox', { name: 'TelÃ©fono' }).fill('4441414141');
  await page.getByRole('textbox', { name: 'TelÃ©fono' }).press('Tab');
  await page.getByLabel('Ciudad').selectOption('MedellÃ­n');
  await expect(page.getByRole('button', { name: 'Continuar al Pago' })).toBeVisible();
  await page.getByRole('button', { name: 'Continuar al Pago' }).click();
  await page.getByRole('textbox', { name: 'NÃºmero de Tarjeta' }).click();
  await page.getByRole('textbox', { name: 'NÃºmero de Tarjeta' }).fill('11111111111111');
  await page.getByRole('textbox', { name: 'Vencimiento' }).click();
  await expect(page.getByText('2. Pago')).toBeVisible();
  await page.getByRole('heading', { name: 'MÃ©todo de Pago' }).click();
  await expect(page.getByRole('heading', { name: 'MÃ©todo de Pago' })).toBeVisible();
  await expect(page.getByText('NÃºmero de Tarjeta')).toBeVisible();
  await expect(page.getByText('Vencimiento')).toBeVisible();
  await page.getByRole('textbox', { name: 'Vencimiento' }).click();
  await page.getByRole('textbox', { name: 'Vencimiento' }).fill('12/30');
  await page.getByRole('textbox', { name: 'Vencimiento' }).press('Tab');
  await page.getByRole('textbox', { name: 'CVV' }).fill('123');
  await expect(page.getByRole('button', { name: 'Confirmar Pedido' })).toBeVisible();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Confirmar Pedido' }).click();
  await expect(page.getByText('Ver detalle â–¼').nth(4)).toBeVisible();
  await page.getByText('Ver detalle â–¼').nth(4).click();
  await expect(page.getByText('Nintendo Switch OLED x1 â€” $ 1')).toBeVisible();
  await page.getByRole('link', { name: 'QAXmarket' }).click();
  await page.getByRole('link', { name: 'Cambiar a Vendedor' }).click();
  await page.getByText('ðŸª').click();
  await page.getByRole('link', { name: 'Ã“rdenes Recibidas' }).click();
  await expect(page.getByRole('link', { name: 'Ã“rdenes Recibidas' })).toBeVisible();
  await page.getByRole('link', { name: 'Ã“rdenes Recibidas' }).click();
  await expect(page.getByRole('button', { name: 'Marcar como Enviado' })).toBeVisible();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Marcar como Enviado' }).click();
  await expect(page.getByText('Enviado')).toBeVisible();
  await expect(page.getByRole('cell', { name: 'Nintendo Switch OLED x1' })).toBeVisible();
});
