import { test, expect } from '@playwright/test';

test('HU-01 codegen base: compra de producto como comprador', async ({ page }) => {
  await page.goto('/index.html');
  await expect(page.getByRole('heading', { name: 'Soy Comprador' })).toBeVisible();
  await page.getByRole('heading', { name: 'Soy Comprador' }).click();
  await expect(page.getByRole('heading', { name: 'Catálogo de Productos' })).toBeVisible();
  await expect(page.getByText('iPhone 14 Pro 128GB')).toBeVisible();
  await expect(page.getByText('$ 4.300.000')).toBeVisible();
  await page.getByRole('textbox', { name: 'Buscar productos...' }).click();
  await page.getByRole('textbox', { name: 'Buscar productos...' }).fill('silla');
  await page.getByRole('textbox', { name: 'Buscar productos...' }).press('Enter');
  await expect(page.getByText('Silla Gamer Corsair T3')).toBeVisible();
  await expect(page.getByText('$')).toBeVisible();
  await page.getByText('📦').click();
  await expect(page.getByRole('button', { name: 'Agregar al Carrito' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Hacer Oferta' })).toBeVisible();
  await expect(page.getByText('Cantidad:')).toBeVisible();
  await expect(page.getByRole('spinbutton', { name: 'Cantidad:' })).toBeVisible();
  await expect(page.getByText('Categoría:')).toBeVisible();
  await page.getByText('Stock:').click();
  await expect(page.getByText('Stock:')).toBeVisible();
  await expect(page.getByText('Vendedor:')).toBeVisible();
  await page.getByRole('button', { name: 'Agregar al Carrito' }).click();
  await page.getByRole('button', { name: 'Agregar al Carrito' }).click();
  await expect(page.getByText('Producto agregado al carrito')).toBeVisible();
  await expect(page.getByRole('link', { name: '🛒 Carrito (2)' })).toBeVisible();
  await page.getByRole('link', { name: '🛒 Carrito (2)' }).click();
  await page.getByRole('spinbutton').click();
  await page.getByRole('spinbutton').click();
  await page.getByRole('spinbutton').fill('1');
  await page.getByText('← Seguir Comprando Comprador Mis Órdenes Carrito de Compras').click();
  await expect(page.getByRole('columnheader', { name: 'Producto' })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Precio' })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Cantidad' })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Subtotal' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Eliminar' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Ir a Pagar' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Ir a Pagar' })).toBeVisible();
  await page.getByRole('link', { name: 'Ir a Pagar' }).click();
  await page.getByRole('textbox', { name: 'Nombre Completo' }).click();
  await page.getByRole('textbox', { name: 'Nombre Completo' }).fill('Luis Zuluaga');
  await page.getByRole('textbox', { name: 'Nombre Completo' }).press('Tab');
  await page.getByRole('textbox', { name: 'Dirección' }).fill('Calle Falsa 123');
  await page.getByRole('textbox', { name: 'Dirección' }).press('Tab');
  await page.getByRole('textbox', { name: 'Teléfono' }).fill('111111111');
  await page.getByRole('textbox', { name: 'Teléfono' }).press('Tab');
  await page.getByLabel('Ciudad').selectOption('Medellín');
  await expect(page.getByText('1. Envío')).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Información de Envío' })).toBeVisible();
  await expect(page.getByText('Nombre Completo')).toBeVisible();
  await expect(page.getByText('Dirección')).toBeVisible();
  await expect(page.getByText('Teléfono')).toBeVisible();
  await expect(page.getByText('Ciudad')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Continuar al Pago' })).toBeVisible();
  await page.getByRole('button', { name: 'Continuar al Pago' }).click();
  await expect(page.getByText('2. Pago')).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Método de Pago' })).toBeVisible();
  await expect(page.getByText('Tarjeta de Débito')).toBeVisible();
  await expect(page.getByText('PSE')).toBeVisible();
  await page.getByRole('textbox', { name: 'Número de Tarjeta' }).click();
  await page.getByRole('textbox', { name: 'Número de Tarjeta' }).fill('1111111111111111');
  await page.getByRole('textbox', { name: 'Vencimiento' }).click();
  await page.getByRole('textbox', { name: 'Vencimiento' }).fill('09/30');
  await expect(page.getByRole('button', { name: 'Confirmar Pedido' })).toBeVisible();
  page.once('dialog', (dialog) => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Confirmar Pedido' }).click();
  await expect(page.getByRole('heading', { name: 'Mis Órdenes' })).toBeVisible();
  await expect(
    page.getByText('Orden #o5 — 2026-07-23ConfirmadoTotal: $ 1.500.000 | Pago: Tarjeta de Cré'),
  ).toBeVisible();
  await expect(page.getByText('Total: $ 1.500.000 | Pago:')).toBeVisible();
  await expect(page.getByText('Luis Zuluaga — Calle Falsa')).toBeVisible();
  await expect(page.getByText('Confirmado').nth(1)).toBeVisible();
  await expect(page.getByText('Ver detalle ▼').nth(4)).toBeVisible();
  await page.getByText('Ver detalle ▼').nth(4).click();
  await expect(page.getByText('Silla Gamer Corsair T3 x1')).toBeVisible();
});